# Generated by Django 5.0.2 on 2025-03-06 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='booking_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='current_booking_state',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.CreateModel(
            name='ChatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('ticket_type', models.CharField(choices=[('ADULT', 'Adult'), ('CHILD', 'Child'), ('SENIOR', 'Senior'), ('STUDENT', 'Student')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('visit_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_reference', models.CharField(max_length=20, unique=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.chatsession')),
            ],
        ),
    ]
