# Generated by Django 5.0.2 on 2025-03-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_booking_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbooking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
